import sys
from PyQt5.QtWidgets import QApplication
from gui import MineMap
from receiver import Connection
from config import ESP_IP, ESP_PORT
import asyncio


async def main():
    connection = Connection(ESP_IP, ESP_PORT)
    asyncio.create_task(connection.run())
    await connection.is_websocket_open.wait()
    await connection.send_data({"cmd": "none"})
    await asyncio.sleep(1)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "forward"})
    await asyncio.sleep(0.025)
    await connection.send_data({"cmd": "left"})
    await asyncio.sleep(0.5)
    await connection.send_data({"cmd": "left"})
    await asyncio.sleep(0.5)
    await connection.send_data({"cmd": "left"})
    await asyncio.sleep(0.5)
    await connection.send_data({"cmd": "left"})
    await asyncio.sleep(0.5)
    await connection.send_data({"cmd": "left"})
    await asyncio.sleep(0.5)
    await connection.send_data({"cmd": "left"})
    await asyncio.sleep(0.5)
    await connection.send_data({"cmd": "left"})
    await asyncio.sleep(0.5)
    await connection.send_data({"cmd": "left"})
    await asyncio.sleep(0.5)
    await connection.send_data({"cmd": "left"})
    await asyncio.sleep(0.5)
    await connection.send_data({"cmd": "left"})
    await asyncio.sleep(0.5)
    await connection.send_data({"cmd": "left"})
    await asyncio.sleep(0.5)
    await connection.send_data({"cmd": "none"})
    await asyncio.sleep(0.5)

    await asyncio.Future()

if __name__ == "__main__":
    asyncio.run(main())
    # app = QApplication(sys.argv)
    # window = MineMap()
    # window.show()
